/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: NORBERTO-3D (https://sketchfab.com/norberto3d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/phoenix-bird-844ba0cf144a413ea92c779f18912042
title: phoenix bird
*/

import React, { useRef ,useEffect} from 'react'
import { useGLTF, useAnimations ,Sparkles} from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const Model = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/phoenix_bird.glb')
  const { actions } = useAnimations(animations, group)
  useFrame((state)=>{
    //state.camera.position.x += -1;
  })
  useEffect(()=>{
    actions["Take 001"].play()
  },[])
  return (
    <>
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" position={[-0.62, 0, -17.14]} rotation={[-Math.PI / 2, 0, 0.05]}>
          <group name="5f59736c86d4457fa045aec4aea6b7e0fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="AMesh_Ride_FengHuang_01" rotation={[-Math.PI / 2, 0, 0]} />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.MatI_Ride_FengHuang_01a} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.MatI_Ride_FengHuang_01b} skeleton={nodes.Object_8.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
    </>
  )
}

useGLTF.preload('/phoenix_bird.glb')

export default Model;