
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Cisco (https://sketchfab.com/Ciscow)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cyberpunk-desk-8bc4ca48b2e244ff8b5ba714a2ec1963
title: Cyberpunk Desk
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group dispose={null}>
      <group {...props} scale = {2}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['1041']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['1042']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['1043']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['1053']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['1054']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['1055']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['1045']} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')

export default Model;